### PR TITLE
fix!: Removed the injected verifier, getVerifier and the PactVerifierProvider have both been removed. Fixes pact-foundation#7

### PR DESCRIPTION
**Pull request by TimothyJones**
This is a stab at fixing what I raised [here](https://github.com/pact-foundation/nestjs-pact/pull/17/files#r1045324774). 

Key points:

* When the app is started, we have to know where (host and port) it was started so that we can create the verifier. This means that I had to remove the injected verifier :(
   * There might be a better way to do this, or a more nest-js way to do it (I don't really know nest).
   * However, I can't really see a clear need for injecting a verifier - I see no use case for injecting different kinds, except for testing.
* Speaking of testing, I removed the tests that asserted on the mocked verifier, since I don't feel they tested much 
    * They're kind of marking their own exam, by just checking that the implementation is the same as the test). 
    * If you disagree, these could be added back in by mocking the `Verifier` class itself.
    
* I brought back the old config type for the reason mentioned in my original comment - but this is still a breaking change because the verifier provider thing goes away.

### CODE REVIEW

**Comment by TimothyJones** [comment]
Oh yeah, also I had to drop back to get-port v5.x, since 6 is pure ESM now, and I couldn't see how to get jest to play nicely with it.

**Review by lennartquerter — APPROVED** [review]
This makes sense :) Thanks for the PR.

**Comment by lennartquerter** [comment]
Do we have any idea of how the Verifier provider is used when consuming this library? I guess everyone just uses the VerifierService abstraction anyway.

**Comment by TimothyJones** [comment]
Yeah, I don't see it mentioned in the documentation. I think it's a fairly safe removal - although technically still breaking, of course.

**Pull request merged**
